-- Auto-generated from kirby_air_ride.apworld (DeDeDK v1.0.0). AP item id -> PopTracker item code.
ITEM_MAPPING = {
	[1] = {{"checkbox_filler_air", "toggle"}},  -- Checkbox Filler (Air Ride)
	[2] = {{"checkbox_filler_top", "toggle"}},  -- Checkbox Filler (Top Ride)
	[3] = {{"checkbox_filler_city", "toggle"}},  -- Checkbox Filler (City Trial)
	[5] = {{"patch_cap_increase", "toggle"}},  -- Patch Cap Increase
	[100] = {{"weight_up_perm", "toggle"}},  -- Permanent Weight Up
	[101] = {{"boost_up_perm", "toggle"}},  -- Permanent Boost Up
	[102] = {{"top_speed_up_perm", "toggle"}},  -- Permanent Top Speed Up
	[103] = {{"turn_up_perm", "toggle"}},  -- Permanent Turn Up
	[104] = {{"charge_up_perm", "toggle"}},  -- Permanent Charge Up
	[105] = {{"glide_up_perm", "toggle"}},  -- Permanent Glide Up
	[106] = {{"offense_up_perm", "toggle"}},  -- Permanent Offense Up
	[107] = {{"defense_up_perm", "toggle"}},  -- Permanent Defense Up
	[108] = {{"hp_up_perm", "toggle"}},  -- Permanent HP Up
	[304] = {{"boost_down", "toggle"}},  -- Boost Down Patch
	[306] = {{"top_speed_down", "toggle"}},  -- Top Speed Down Patch
	[308] = {{"offense_down", "toggle"}},  -- Offense Down Patch
	[310] = {{"defense_down", "toggle"}},  -- Defense Down Patch
	[312] = {{"turn_down", "toggle"}},  -- Turn Down Patch
	[314] = {{"glide_down", "toggle"}},  -- Glide Down Patch
	[316] = {{"charge_down", "toggle"}},  -- Charge Down Patch
	[318] = {{"weight_down", "toggle"}},  -- Weight Down Patch
	[400] = {{"stadium_drag_race_1", "toggle"}},  -- Unlock Stadium: DRAG RACE 1
	[401] = {{"stadium_drag_race_2", "toggle"}},  -- Unlock Stadium: DRAG RACE 2
	[402] = {{"stadium_drag_race_3", "toggle"}},  -- Unlock Stadium: DRAG RACE 3
	[403] = {{"stadium_drag_race_4", "toggle"}},  -- Unlock Stadium: DRAG RACE 4
	[404] = {{"stadium_air_glider", "toggle"}},  -- Unlock Stadium: AIR GLIDER
	[405] = {{"stadium_target_flight", "toggle"}},  -- Unlock Stadium: TARGET FLIGHT
	[406] = {{"stadium_high_jump", "toggle"}},  -- Unlock Stadium: HIGH JUMP
	[407] = {{"stadium_kirby_melee_1", "toggle"}},  -- Unlock Stadium: KIRBY MELEE 1
	[408] = {{"stadium_kirby_melee_2", "toggle"}},  -- Unlock Stadium: KIRBY MELEE 2
	[409] = {{"stadium_destruction_derby_1", "toggle"}},  -- Unlock Stadium: DESTRUCTION DERBY 1
	[410] = {{"stadium_destruction_derby_2", "toggle"}},  -- Unlock Stadium: DESTRUCTION DERBY 2
	[411] = {{"stadium_destruction_derby_3", "toggle"}},  -- Unlock Stadium: DESTRUCTION DERBY 3
	[412] = {{"stadium_destruction_derby_4", "toggle"}},  -- Unlock Stadium: DESTRUCTION DERBY 4
	[413] = {{"stadium_destruction_derby_5", "toggle"}},  -- Unlock Stadium: DESTRUCTION DERBY 5
	[414] = {{"stadium_single_race_1", "toggle"}},  -- Unlock Stadium: SINGLE RACE 1
	[415] = {{"stadium_single_race_2", "toggle"}},  -- Unlock Stadium: SINGLE RACE 2
	[416] = {{"stadium_single_race_3", "toggle"}},  -- Unlock Stadium: SINGLE RACE 3
	[417] = {{"stadium_single_race_4", "toggle"}},  -- Unlock Stadium: SINGLE RACE 4
	[418] = {{"stadium_single_race_5", "toggle"}},  -- Unlock Stadium: SINGLE RACE 5
	[419] = {{"stadium_single_race_6", "toggle"}},  -- Unlock Stadium: SINGLE RACE 6
	[420] = {{"stadium_single_race_7", "toggle"}},  -- Unlock Stadium: SINGLE RACE 7
	[421] = {{"stadium_single_race_8", "toggle"}},  -- Unlock Stadium: SINGLE RACE 8
	[422] = {{"stadium_single_race_9", "toggle"}},  -- Unlock Stadium: SINGLE RACE 9
	[423] = {{"stadium_vs_king_dedede", "toggle"}},  -- Unlock Stadium: VS. KING DEDEDE
	[500] = {{"map_air_ride_nebula_belt", "toggle"}},  -- Air Ride Reward: Nebula Belt Course
	[502] = {{"character_unlock_meta_knight", "toggle"}},  -- Air Ride Reward: Meta Knight
	[504] = {{"character_unlock_king_dedede", "toggle"}},  -- Air Ride Reward: King Dedede
	[505] = {{"kirby_green", "toggle"}},  -- Air Ride Reward: Green Kirby
	[506] = {{"machine_wagon_star", "toggle"}},  -- Air Ride Reward: Wagon Star
	[509] = {{"machine_rex_wheelie", "toggle"}},  -- Air Ride Reward: Rex Wheelie
	[510] = {{"kirby_purple", "toggle"}},  -- Air Ride Reward: Purple Kirby
	[511] = {{"machine_slick_star", "toggle"}},  -- Air Ride Reward: Slick Star
	[513] = {{"kirby_white", "toggle"}},  -- Air Ride Reward: White Kirby
	[514] = {{"machine_swerve_star", "toggle"}},  -- Air Ride Reward: Swerve Star
	[515] = {{"machine_shadow_star", "toggle"}},  -- Air Ride Reward: Shadow Star
	[516] = {{"machine_jet_star", "toggle"}},  -- Air Ride Reward: Jet Star
	[520] = {{"machine_bulk_star", "toggle"}},  -- Air Ride Reward: Bulk Star
	[522] = {{"machine_formula_star", "toggle"}},  -- Air Ride Reward: Formula Star
	[528] = {{"kirby_brown", "toggle"}},  -- Air Ride Reward: Brown Kirby
	[531] = {{"machine_rocket_star", "toggle"}},  -- Air Ride Reward: Rocket Star
	[533] = {{"machine_wheelie_bike", "toggle"}},  -- Air Ride Reward: Wheelie Bike
	[534] = {{"machine_scooter_bike", "toggle"}},  -- Air Ride Reward: Wheelie Scooter
	[535] = {{"machine_winged_star", "toggle"}},  -- Air Ride Reward: Winged Star
	[541] = {{"machine_turbo_star", "toggle"}},  -- Air Ride Reward: Turbo Star
	[550] = {{"kirby_green", "toggle"}},  -- Top Ride Reward: Green Kirby
	[551] = {{"kirby_purple", "toggle"}},  -- Top Ride Reward: Purple Kirby
	[554] = {{"top_ride_item_lantern", "toggle"}},  -- Top Ride Reward: Lantern Item
	[557] = {{"top_ride_item_chickie", "toggle"}},  -- Top Ride Reward: Chickie Item
	[562] = {{"kirby_brown", "toggle"}},  -- Top Ride Reward: Brown Kirby
	[574] = {{"kirby_white", "toggle"}},  -- Top Ride Reward: White Kirby
	[611] = {{"stadium_drag_race_4", "toggle"}},  -- City Trial Reward: Drag Race 4 Stadium
	[613] = {{"part_dragoon_a", "toggle"}},  -- City Trial Reward: Dragoon Part A
	[615] = {{"part_dragoon_c", "toggle"}},  -- City Trial Reward: Dragoon Part C
	[617] = {{"stadium_destruction_derby_4", "toggle"}},  -- City Trial Reward: Destruction Derby 4 Stadium
	[619] = {{"part_hydra_y", "toggle"}},  -- City Trial Reward: Hydra Part Y
	[621] = {{"part_hydra_z", "toggle"}},  -- City Trial Reward: Hydra Part Z
	[629] = {{"part_dragoon_b", "toggle"}},  -- City Trial Reward: Dragoon Part B
	[631] = {{"part_hydra_x", "toggle"}},  -- City Trial Reward: Hydra Part X
	[632] = {{"kirby_purple", "toggle"}},  -- City Trial Reward: Purple Kirby
	[633] = {{"stadium_destruction_derby_3", "toggle"}},  -- City Trial Reward: Destruction Derby 3 Stadium
	[634] = {{"stadium_destruction_derby_5", "toggle"}},  -- City Trial Reward: Destruction Derby 5 Stadium
	[635] = {{"stadium_kirby_melee_2", "toggle"}},  -- City Trial Reward: Kirby Melee 2 Stadium
	[637] = {{"kirby_green", "toggle"}},  -- City Trial Reward: Green Kirby
	[638] = {{"kirby_brown", "toggle"}},  -- City Trial Reward: Brown Kirby
	[643] = {{"kirby_white", "toggle"}},  -- City Trial Reward: White Kirby
	[700] = {{"event_dyna_blade", "toggle"}},  -- Unlock Event: Dyna Blade
	[701] = {{"event_tac", "toggle"}},  -- Unlock Event: Tac
	[702] = {{"event_meteor_impact", "toggle"}},  -- Unlock Event: Meteor
	[703] = {{"event_huge_pillar", "toggle"}},  -- Unlock Event: Pillar
	[704] = {{"event_run_amok", "toggle"}},  -- Unlock Event: Run Amok
	[705] = {{"event_restoration_area", "toggle"}},  -- Unlock Event: Restoration Area
	[706] = {{"event_rails_on_fire", "toggle"}},  -- Unlock Event: Rail Fire
	[707] = {{"event_same_items", "toggle"}},  -- Unlock Event: Same Item
	[708] = {{"event_lighthouse", "toggle"}},  -- Unlock Event: Lighthouse
	[709] = {{"event_secret_chamber", "toggle"}},  -- Unlock Event: Secret Chamber
	[710] = {{"event_prediction", "toggle"}},  -- Unlock Event: Prediction
	[711] = {{"event_air_ride_formation", "toggle"}},  -- Unlock Event: Machine Formation
	[712] = {{"event_ufo", "toggle"}},  -- Unlock Event: UFO
	[713] = {{"event_box_bounce", "toggle"}},  -- Unlock Event: Bounce
	[714] = {{"event_dense_fog", "toggle"}},  -- Unlock Event: Fog
	[715] = {{"event_fake_items", "toggle"}},  -- Unlock Event: Fake Powerups
	[760] = {{"ability_fire", "toggle"}},  -- Unlock Copy Ability: Fire
	[761] = {{"ability_wheel", "toggle"}},  -- Unlock Copy Ability: Wheel
	[762] = {{"ability_sleep", "toggle"}},  -- Unlock Copy Ability: Sleep
	[763] = {{"ability_sword", "toggle"}},  -- Unlock Copy Ability: Sword
	[764] = {{"ability_bomb", "toggle"}},  -- Unlock Copy Ability: Bomb
	[765] = {{"ability_plasma", "toggle"}},  -- Unlock Copy Ability: Plasma
	[766] = {{"ability_needle", "toggle"}},  -- Unlock Copy Ability: Needle
	[767] = {{"ability_mike", "toggle"}},  -- Unlock Copy Ability: Mic
	[768] = {{"ability_freeze", "toggle"}},  -- Unlock Copy Ability: Freeze
	[769] = {{"ability_tornado", "toggle"}},  -- Unlock Copy Ability: Tornado
	[770] = {{"ability_wing", "toggle"}},  -- Unlock Copy Ability: Wing
	[780] = {{"patch_unlock_weight", "toggle"}},  -- Unlock Patch: Weight
	[781] = {{"patch_unlock_boost", "toggle"}},  -- Unlock Patch: Boost
	[782] = {{"patch_unlock_top_speed", "toggle"}},  -- Unlock Patch: Top Speed
	[783] = {{"patch_unlock_turn", "toggle"}},  -- Unlock Patch: Turn
	[784] = {{"patch_unlock_charge", "toggle"}},  -- Unlock Patch: Charge
	[785] = {{"patch_unlock_glide", "toggle"}},  -- Unlock Patch: Glide
	[786] = {{"patch_unlock_offense", "toggle"}},  -- Unlock Patch: Offense
	[787] = {{"patch_unlock_defense", "toggle"}},  -- Unlock Patch: Defense
	[788] = {{"patch_unlock_hp", "toggle"}},  -- Unlock Patch: HP
	[790] = {{"all_up", "toggle"}},  -- Unlock Item: All Up
	[791] = {{"special_offense_speed_up", "toggle"}},  -- Unlock Item: Speed Max
	[793] = {{"special_offense_attack_up", "toggle"}},  -- Unlock Item: Offense Max
	[794] = {{"special_offense_defense_up", "toggle"}},  -- Unlock Item: Defense Max
	[795] = {{"special_offense_run_amok", "toggle"}},  -- Unlock Item: Charge Max
	[796] = {{"special_offense_no_charge", "toggle"}},  -- Unlock Item: Charge None
	[797] = {{"special_offense_candy", "toggle"}},  -- Unlock Item: Candy
	[798] = {{"food_maxim_tomato", "toggle"}},  -- Unlock Item: Maxim Tomato
	[799] = {{"food_energy_drink", "toggle"}},  -- Unlock Item: Energy Drink
	[800] = {{"food_ice_cream_cone", "toggle"}},  -- Unlock Item: Ice Cream
	[801] = {{"food_rice_ball", "toggle"}},  -- Unlock Item: Rice Ball
	[802] = {{"food_roast_chicken", "toggle"}},  -- Unlock Item: Chicken
	[803] = {{"food_curry", "toggle"}},  -- Unlock Item: Curry
	[804] = {{"food_ramen", "toggle"}},  -- Unlock Item: Ramen
	[805] = {{"food_omelet", "toggle"}},  -- Unlock Item: Omelet
	[806] = {{"food_hamburger", "toggle"}},  -- Unlock Item: Hamburger
	[807] = {{"food_sushi", "toggle"}},  -- Unlock Item: Sushi
	[808] = {{"food_hotdog", "toggle"}},  -- Unlock Item: Hot Dog
	[809] = {{"food_apple", "toggle"}},  -- Unlock Item: Apple
	[810] = {{"special_offense_fireworks", "toggle"}},  -- Unlock Item: Fireworks
	[811] = {{"special_offense_panic_spin", "toggle"}},  -- Unlock Item: Panic Spin
	[812] = {{"special_offense_sensor_bomb", "toggle"}},  -- Unlock Item: Sensor Bomb
	[813] = {{"special_offense_gold_spike", "toggle"}},  -- Unlock Item: Gordo
	[814] = {{"part_hydra_x", "toggle"}},  -- Unlock Item: Hydra Part X
	[815] = {{"part_hydra_y", "toggle"}},  -- Unlock Item: Hydra Part Y
	[816] = {{"part_hydra_z", "toggle"}},  -- Unlock Item: Hydra Part Z
	[817] = {{"part_dragoon_a", "toggle"}},  -- Unlock Item: Dragoon Part A
	[818] = {{"part_dragoon_b", "toggle"}},  -- Unlock Item: Dragoon Part B
	[819] = {{"part_dragoon_c", "toggle"}},  -- Unlock Item: Dragoon Part C
	[830] = {{"machine_warp_star", "toggle"}},  -- Unlock Machine: Warp Star
	[831] = {{"machine_compact_star", "toggle"}},  -- Unlock Machine: Compact Star
	[832] = {{"machine_winged_star", "toggle"}},  -- Unlock Machine: Winged Star
	[833] = {{"machine_shadow_star", "toggle"}},  -- Unlock Machine: Shadow Star
	[834] = {{"machine_hydra", "toggle"}},  -- Unlock Machine: Hydra
	[835] = {{"machine_bulk_star", "toggle"}},  -- Unlock Machine: Bulk Star
	[836] = {{"machine_slick_star", "toggle"}},  -- Unlock Machine: Slick Star
	[837] = {{"machine_formula_star", "toggle"}},  -- Unlock Machine: Formula Star
	[838] = {{"machine_dragoon", "toggle"}},  -- Unlock Machine: Dragoon
	[839] = {{"machine_wagon_star", "toggle"}},  -- Unlock Machine: Wagon Star
	[840] = {{"machine_rocket_star", "toggle"}},  -- Unlock Machine: Rocket Star
	[841] = {{"machine_swerve_star", "toggle"}},  -- Unlock Machine: Swerve Star
	[842] = {{"machine_turbo_star", "toggle"}},  -- Unlock Machine: Turbo Star
	[843] = {{"machine_jet_star", "toggle"}},  -- Unlock Machine: Jet Star
	[844] = {{"machine_flight_warp_star", "toggle"}},  -- Unlock Machine: Flight Warp Star
	[845] = {{"machine_free_star", "toggle"}},  -- Unlock Machine: Free Star
	[846] = {{"machine_steer_star", "toggle"}},  -- Unlock Machine: Steer Star
	[848] = {{"character_unlock_meta_knight", "toggle"}},   -- Unlock Machine: Meta Knight
	[851] = {{"machine_wheelie_bike", "toggle"}},  -- Unlock Machine: Wheelie Bike
	[852] = {{"machine_rex_wheelie", "toggle"}},  -- Unlock Machine: Rex Wheelie
	[853] = {{"machine_scooter_bike", "toggle"}},  -- Unlock Machine: Wheelie Scooter
	[854] = {{"character_unlock_king_dedede", "toggle"}},  -- Unlock Machine: King Dedede
	[860] = {{"box_blue", "toggle"}},  -- Unlock Box: Blue
	[861] = {{"box_green", "toggle"}},  -- Unlock Box: Green
	[862] = {{"box_red", "toggle"}},  -- Unlock Box: Red
	[870] = {{"map_air_ride_fantasy_meadows", "toggle"}},  -- Unlock AR Course: Fantasy Meadows
	[871] = {{"map_air_ride_magma_flows", "toggle"}},  -- Unlock AR Course: Magma Flows
	[872] = {{"map_air_ride_sky_sands", "toggle"}},  -- Unlock AR Course: Sky Sands
	[873] = {{"map_air_ride_frozen_hillside", "toggle"}},  -- Unlock AR Course: Frozen Hillside
	[874] = {{"map_air_ride_beanstalk_park", "toggle"}},  -- Unlock AR Course: Beanstalk Park
	[875] = {{"map_air_ride_celestial_valley", "toggle"}},  -- Unlock AR Course: Celestial Valley
	[876] = {{"map_air_ride_machine_passage", "toggle"}},  -- Unlock AR Course: Machine Passage
	[877] = {{"map_air_ride_checkered_knights", "toggle"}},  -- Unlock AR Course: Checker Knights
	[878] = {{"map_air_ride_nebula_belt", "toggle"}},  -- Unlock AR Course: Nebula Belt
	[880] = {{"kirby_pink", "toggle"}},  -- Unlock Kirby Color: Pink
	[881] = {{"kirby_yellow", "toggle"}},  -- Unlock Kirby Color: Yellow
	[882] = {{"kirby_blue", "toggle"}},  -- Unlock Kirby Color: Blue
	[883] = {{"kirby_red", "toggle"}},  -- Unlock Kirby Color: Red
	[884] = {{"kirby_green", "toggle"}},  -- Unlock Kirby Color: Green
	[885] = {{"kirby_purple", "toggle"}},  -- Unlock Kirby Color: Purple
	[886] = {{"kirby_brown", "toggle"}},  -- Unlock Kirby Color: Brown
	[887] = {{"kirby_white", "toggle"}},  -- Unlock Kirby Color: White
	[890] = {{"map_top_ride_grass", "toggle"}},  -- Unlock TR Course: Grass
	[891] = {{"map_top_ride_sand", "toggle"}},  -- Unlock TR Course: Sand
	[892] = {{"map_top_ride_sky", "toggle"}},  -- Unlock TR Course: Sky
	[893] = {{"map_top_ride_fire", "toggle"}},  -- Unlock TR Course: Fire
	[894] = {{"map_top_ride_light", "toggle"}},  -- Unlock TR Course: Light
	[895] = {{"map_top_ride_water", "toggle"}},  -- Unlock TR Course: Water
	[896] = {{"map_top_ride_metal", "toggle"}},  -- Unlock TR Course: Metal
	[900] = {{"top_ride_item_hammer", "toggle"}},  -- Unlock TR Item: Hammer
	[901] = {{"top_ride_item_big_cake", "toggle"}},  -- Unlock TR Item: Big Cake
	[902] = {{"top_ride_item_speed_up", "toggle"}},  -- Unlock TR Item: Speed Up
	[903] = {{"top_ride_item_speed_down", "toggle"}},  -- Unlock TR Item: Speed Down
	[904] = {{"top_ride_item_spinner", "toggle"}},  -- Unlock TR Item: Spinner
	[905] = {{"top_ride_item_charge_up", "toggle"}},  -- Unlock TR Item: Charge Tank
	[906] = {{"top_ride_item_invincible_candy", "toggle"}},  -- Unlock TR Item: Invincible Candy
	[907] = {{"top_ride_item_buzz_saw", "toggle"}},  -- Unlock TR Item: Buzz Saw
	[908] = {{"top_ride_item_drill", "toggle"}},  -- Unlock TR Item: Drill
	[910] = {{"top_ride_item_missile", "toggle"}},  -- Unlock TR Item: Missile
	[915] = {{"top_ride_item_lantern", "toggle"}},  -- Unlock TR Item: Lantern
	[917] = {{"top_ride_item_krako", "toggle"}},  -- Unlock TR Item: Kracko
	[919] = {{"top_ride_item_smokescreen", "toggle"}},  -- Unlock TR Item: Smokescreen
	[920] = {{"top_ride_item_chickie", "toggle"}},  -- Unlock TR Item: Chickie
	[921] = {{"top_ride_item_party_ball", "toggle"}},  -- Unlock TR Item: Party Ball
	[972] = {{"filler", "toggle"}},  -- Big Kirby
	[973] = {{"filler", "toggle"}},  -- Small Kirby
}
